// Sumber: kenkyu-H29_kaigono_nihongo_multi_1117.pdf
// 267 kosakata kaigo untuk jisshuusei

const VOCABULARY = [

  // =============================================
  // KATEGORI: tubuh_luar (Bagian luar tubuh)
  // =============================================
  { id:"001", kanji:"髪の毛",   yomkata:"かみのけ",      arti:"rambut",               contoh:"髪の毛をとかしましょうか。",           contoh_arti:"Boleh saya sisirkan rambut Anda?",          kategori:"tubuh_luar" },
  { id:"002", kanji:"首",       yomkata:"くび",          arti:"leher",                contoh:"首が痛いですか。",                       contoh_arti:"Apakah leher Anda sakit?",                  kategori:"tubuh_luar" },
  { id:"003", kanji:"わきの下", yomkata:"わきのした",    arti:"ketiak",               contoh:"わきの下を拭きますね。",                  contoh_arti:"Saya lap ketek Anda ya.",                   kategori:"tubuh_luar" },
  { id:"004", kanji:"腕",       yomkata:"うで",          arti:"lengan",               contoh:"腕を上げてください。",                    contoh_arti:"Tolong angkat lengan Anda.",                kategori:"tubuh_luar" },
  { id:"005", kanji:"肘",       yomkata:"ひじ",          arti:"siku",                 contoh:"肘を曲げますね。",                        contoh_arti:"Saya tekuk siku Anda ya.",                  kategori:"tubuh_luar" },
  { id:"006", kanji:"へそ",     yomkata:"へそ",          arti:"pusar",                contoh:"へそのまわりを拭きます。",                contoh_arti:"Saya lap area sekitar pusar.",              kategori:"tubuh_luar" },
  { id:"007", kanji:"腰",       yomkata:"こし",          arti:"pinggang",             contoh:"腰が痛いですか。",                        contoh_arti:"Apakah pinggang Anda sakit?",               kategori:"tubuh_luar" },
  { id:"008", kanji:"背中",     yomkata:"せなか",        arti:"punggung",             contoh:"背中を洗いますね。",                      contoh_arti:"Saya cuci punggung Anda ya.",               kategori:"tubuh_luar" },
  { id:"009", kanji:"頭",       yomkata:"あたま",        arti:"kepala",               contoh:"頭は痛くないですか。",                    contoh_arti:"Kepala Anda tidak sakit?",                  kategori:"tubuh_luar" },
  { id:"010", kanji:"肩",       yomkata:"かた",          arti:"bahu",                 contoh:"肩をマッサージしましょうか。",            contoh_arti:"Boleh saya pijat bahu Anda?",               kategori:"tubuh_luar" },
  { id:"011", kanji:"胸",       yomkata:"むね",          arti:"dada",                 contoh:"胸が苦しくないですか。",                  contoh_arti:"Dada Anda tidak sesak?",                    kategori:"tubuh_luar" },
  { id:"012", kanji:"腹",       yomkata:"はら",          arti:"perut",                contoh:"お腹は痛いですか。",                      contoh_arti:"Apakah perut Anda sakit?",                  kategori:"tubuh_luar" },
  { id:"013", kanji:"尻",       yomkata:"しり",          arti:"pantat",               contoh:"お尻を拭きますね。",                      contoh_arti:"Saya lap pantat Anda ya.",                  kategori:"tubuh_luar" },
  { id:"014", kanji:"ひたい",   yomkata:"ひたい",        arti:"dahi",                 contoh:"ひたいを拭きますね。",                    contoh_arti:"Saya lap dahi Anda ya.",                    kategori:"tubuh_luar" },
  { id:"015", kanji:"まゆ毛",   yomkata:"まゆげ",        arti:"alis",                 contoh:"まゆ毛をそりましょうか。",               contoh_arti:"Boleh saya cukur alis Anda?",               kategori:"tubuh_luar" },
  { id:"016", kanji:"まつ毛",   yomkata:"まつげ",        arti:"bulu mata",            contoh:"まつ毛に何かついていますか。",            contoh_arti:"Ada sesuatu yang menempel di bulu mata?",   kategori:"tubuh_luar" },
  { id:"017", kanji:"鼻",       yomkata:"はな",          arti:"hidung",               contoh:"鼻をかみましょうか。",                    contoh_arti:"Boleh saya bersihkan hidung Anda?",         kategori:"tubuh_luar" },
  { id:"018", kanji:"口",       yomkata:"くち",          arti:"mulut",                contoh:"口を開けてください。",                    contoh_arti:"Tolong buka mulut Anda.",                   kategori:"tubuh_luar" },
  { id:"019", kanji:"歯",       yomkata:"は",            arti:"gigi",                 contoh:"歯を磨きましょうか。",                    contoh_arti:"Boleh saya sikat gigi Anda?",               kategori:"tubuh_luar" },
  { id:"020", kanji:"あご",     yomkata:"あご",          arti:"dagu",                 contoh:"あごを持ちますね。",                      contoh_arti:"Saya pegang dagu Anda ya.",                 kategori:"tubuh_luar" },
  { id:"021", kanji:"顔",       yomkata:"かお",          arti:"wajah",                contoh:"顔を拭きますね。",                        contoh_arti:"Saya lap wajah Anda ya.",                   kategori:"tubuh_luar" },
  { id:"022", kanji:"目",       yomkata:"め",            arti:"mata",                 contoh:"目を閉じてください。",                    contoh_arti:"Tolong tutup mata Anda.",                   kategori:"tubuh_luar" },
  { id:"023", kanji:"耳",       yomkata:"みみ",          arti:"telinga",              contoh:"耳を押さえてください。",                  contoh_arti:"Tolong tutup telinga Anda.",                kategori:"tubuh_luar" },
  { id:"024", kanji:"ほほ",     yomkata:"ほほ",          arti:"pipi",                 contoh:"ほほが赤くなっていますね。",              contoh_arti:"Pipi Anda menjadi merah ya.",               kategori:"tubuh_luar" },
  { id:"025", kanji:"唇",       yomkata:"くちびる",      arti:"bibir",                contoh:"唇が乾いていますよ。",                   contoh_arti:"Bibir Anda kering ya.",                     kategori:"tubuh_luar" },
  { id:"026", kanji:"喉",       yomkata:"のど",          arti:"tenggorokan",          contoh:"喉は痛いですか。",                        contoh_arti:"Apakah tenggorokan Anda sakit?",            kategori:"tubuh_luar" },
  { id:"027", kanji:"手",       yomkata:"て",            arti:"tangan",               contoh:"手を洗いましょうか。",                    contoh_arti:"Boleh kita cuci tangan?",                   kategori:"tubuh_luar" },
  { id:"028", kanji:"指",       yomkata:"ゆび",          arti:"jari",                 contoh:"指を動かせますか。",                      contoh_arti:"Bisakah Anda menggerakkan jari?",           kategori:"tubuh_luar" },
  { id:"029", kanji:"爪",       yomkata:"つめ",          arti:"kuku",                 contoh:"爪を切りましょうか。",                    contoh_arti:"Boleh saya potong kuku Anda?",              kategori:"tubuh_luar" },
  { id:"030", kanji:"手の甲",   yomkata:"てのこう",      arti:"punggung tangan",      contoh:"手の甲が赤いですね。",                   contoh_arti:"Punggung tangan Anda merah ya.",            kategori:"tubuh_luar" },
  { id:"031", kanji:"手首",     yomkata:"てくび",        arti:"pergelangan tangan",   contoh:"手首を持ちますね。",                      contoh_arti:"Saya pegang pergelangan tangan ya.",        kategori:"tubuh_luar" },
  { id:"032", kanji:"手のひら", yomkata:"てのひら",      arti:"telapak tangan",       contoh:"手のひらを見せてください。",              contoh_arti:"Tolong tunjukkan telapak tangan Anda.",    kategori:"tubuh_luar" },
  { id:"033", kanji:"親指",     yomkata:"おやゆび",      arti:"ibu jari",             contoh:"親指を曲げてください。",                  contoh_arti:"Tolong tekuk ibu jari Anda.",               kategori:"tubuh_luar" },
  { id:"034", kanji:"人差し指", yomkata:"ひとさしゆび",  arti:"jari telunjuk",        contoh:"人差し指で指してください。",              contoh_arti:"Tolong tunjuk dengan jari telunjuk.",       kategori:"tubuh_luar" },
  { id:"035", kanji:"中指",     yomkata:"なかゆび",      arti:"jari tengah",          contoh:"中指が痛いですか。",                      contoh_arti:"Apakah jari tengah Anda sakit?",            kategori:"tubuh_luar" },
  { id:"036", kanji:"薬指",     yomkata:"くすりゆび",    arti:"jari manis",           contoh:"薬指に指輪がありますか。",                contoh_arti:"Apakah ada cincin di jari manis?",          kategori:"tubuh_luar" },
  { id:"037", kanji:"小指",     yomkata:"こゆび",        arti:"jari kelingking",      contoh:"小指は動きますか。",                      contoh_arti:"Bisakah jari kelingking bergerak?",         kategori:"tubuh_luar" },
  { id:"038", kanji:"太もも",   yomkata:"ふともも",      arti:"paha",                 contoh:"太ももをさすりますね。",                  contoh_arti:"Saya usap paha Anda ya.",                   kategori:"tubuh_luar" },
  { id:"039", kanji:"ふくらはぎ",yomkata:"ふくらはぎ",  arti:"betis",                contoh:"ふくらはぎが張っていますか。",            contoh_arti:"Apakah betis Anda tegang?",                 kategori:"tubuh_luar" },
  { id:"040", kanji:"足首",     yomkata:"あしくび",      arti:"pergelangan kaki",     contoh:"足首を動かしてみましょう。",              contoh_arti:"Coba gerakkan pergelangan kaki.",           kategori:"tubuh_luar" },
  { id:"041", kanji:"膝",       yomkata:"ひざ",          arti:"lutut",                contoh:"膝を曲げますね。",                        contoh_arti:"Saya tekuk lutut Anda ya.",                 kategori:"tubuh_luar" },
  { id:"042", kanji:"足の裏",   yomkata:"あしのうら",    arti:"telapak kaki",         contoh:"足の裏をマッサージしましょうか。",        contoh_arti:"Boleh saya pijat telapak kaki?",            kategori:"tubuh_luar" },
  { id:"043", kanji:"つま先",   yomkata:"つまさき",      arti:"ujung jari kaki",      contoh:"つま先が冷たいですか。",                  contoh_arti:"Apakah ujung jari kaki Anda dingin?",       kategori:"tubuh_luar" },
  { id:"044", kanji:"かかと",   yomkata:"かかと",        arti:"tumit",                contoh:"かかとに傷がありますよ。",               contoh_arti:"Ada luka di tumit Anda.",                   kategori:"tubuh_luar" },

  // =============================================
  // KATEGORI: tubuh_dalam (Organ dalam)
  // =============================================
  { id:"045", kanji:"筋肉",  yomkata:"きんにく",   arti:"otot",           contoh:"筋肉が固くなっていますよ。",       contoh_arti:"Otot Anda menjadi kaku ya.",          kategori:"tubuh_dalam" },
  { id:"046", kanji:"骨",    yomkata:"ほね",       arti:"tulang",         contoh:"骨が折れていないか確認します。",   contoh_arti:"Saya periksa apakah tulang patah.",   kategori:"tubuh_dalam" },
  { id:"047", kanji:"関節",  yomkata:"かんせつ",   arti:"sendi",          contoh:"関節が痛いですか。",               contoh_arti:"Apakah sendi Anda sakit?",            kategori:"tubuh_dalam" },
  { id:"048", kanji:"心臓",  yomkata:"しんぞう",   arti:"jantung",        contoh:"心臓の音を聞きますね。",           contoh_arti:"Saya dengarkan bunyi jantung ya.",    kategori:"tubuh_dalam" },
  { id:"049", kanji:"血液",  yomkata:"けつえき",   arti:"darah",          contoh:"血液検査をします。",               contoh_arti:"Kami akan melakukan tes darah.",      kategori:"tubuh_dalam" },
  { id:"050", kanji:"血管",  yomkata:"けっかん",   arti:"pembuluh darah", contoh:"血管が細いですね。",               contoh_arti:"Pembuluh darah Anda halus ya.",       kategori:"tubuh_dalam" },
  { id:"051", kanji:"胃",    yomkata:"い",         arti:"lambung",        contoh:"胃が痛いですか。",                 contoh_arti:"Apakah lambung Anda sakit?",          kategori:"tubuh_dalam" },
  { id:"052", kanji:"脳",    yomkata:"のう",       arti:"otak",           contoh:"脳のCTを撮ります。",               contoh_arti:"Kami akan rontgen otak.",             kategori:"tubuh_dalam" },
  { id:"053", kanji:"気管",  yomkata:"きかん",     arti:"trakea",         contoh:"気管に食べ物が入らないように。",   contoh_arti:"Agar makanan tidak masuk ke trakea.", kategori:"tubuh_dalam" },
  { id:"054", kanji:"気管支",yomkata:"きかんし",   arti:"bronkus",        contoh:"気管支が炎症しています。",         contoh_arti:"Bronkus Anda meradang.",              kategori:"tubuh_dalam" },
  { id:"055", kanji:"食道",  yomkata:"しょくどう", arti:"kerongkongan",   contoh:"食道が狭くなっています。",         contoh_arti:"Kerongkongan Anda menyempit.",        kategori:"tubuh_dalam" },
  { id:"056", kanji:"肺",    yomkata:"はい",       arti:"paru-paru",      contoh:"肺の音を聞きますね。",             contoh_arti:"Saya dengarkan bunyi paru-paru ya.",  kategori:"tubuh_dalam" },
  { id:"057", kanji:"肝臓",  yomkata:"かんぞう",   arti:"hati/liver",     contoh:"肝臓の数値が高いですね。",         contoh_arti:"Nilai hati Anda tinggi ya.",          kategori:"tubuh_dalam" },
  { id:"058", kanji:"腎臓",  yomkata:"じんぞう",   arti:"ginjal",         contoh:"腎臓の働きを確認します。",         contoh_arti:"Saya periksa fungsi ginjal.",         kategori:"tubuh_dalam" },
  { id:"059", kanji:"小腸",  yomkata:"しょうちょう",arti:"usus kecil",    contoh:"小腸で栄養を吸収します。",         contoh_arti:"Nutrisi diserap di usus kecil.",      kategori:"tubuh_dalam" },
  { id:"060", kanji:"大腸",  yomkata:"だいちょう", arti:"usus besar",     contoh:"大腸の検査をします。",             contoh_arti:"Kami akan periksa usus besar.",       kategori:"tubuh_dalam" },
  { id:"061", kanji:"膀胱",  yomkata:"ぼうこう",   arti:"kandung kemih",  contoh:"膀胱に尿がたまっています。",       contoh_arti:"Kandung kemih Anda penuh.",           kategori:"tubuh_dalam" },
  { id:"062", kanji:"直腸",  yomkata:"ちょくちょう",arti:"rektum",        contoh:"直腸に便がありますよ。",           contoh_arti:"Ada kotoran di rektum Anda.",         kategori:"tubuh_dalam" },
  { id:"063", kanji:"肛門",  yomkata:"こうもん",   arti:"anus",           contoh:"肛門のまわりを拭きますね。",       contoh_arti:"Saya lap sekitar anus Anda ya.",      kategori:"tubuh_dalam" },

  // =============================================
  // KATEGORI: kondisi_tubuh (Kondisi & pemeriksaan)
  // =============================================
  { id:"064", kanji:"吐き気", yomkata:"はきけ",    arti:"mual",                    contoh:"吐き気がありますか。",           contoh_arti:"Apakah Anda mual?",                  kategori:"kondisi_tubuh" },
  { id:"065", kanji:"痰",     yomkata:"たん",      arti:"dahak",                   contoh:"痰が出ていますか。",             contoh_arti:"Apakah ada dahak yang keluar?",       kategori:"kondisi_tubuh" },
  { id:"066", kanji:"熱",     yomkata:"ねつ",      arti:"demam",                   contoh:"熱がありますよ、38度です。",     contoh_arti:"Anda demam, 38 derajat.",             kategori:"kondisi_tubuh" },
  { id:"067", kanji:"咳",     yomkata:"せき",      arti:"batuk",                   contoh:"咳が出ていますか。",             contoh_arti:"Apakah Anda batuk?",                  kategori:"kondisi_tubuh" },
  { id:"068", kanji:"痛み",   yomkata:"いたみ",    arti:"rasa sakit/nyeri",        contoh:"痛みはありますか。",             contoh_arti:"Apakah ada rasa nyeri?",              kategori:"kondisi_tubuh" },
  { id:"069", kanji:"かゆみ", yomkata:"かゆみ",    arti:"rasa gatal",              contoh:"かゆみがありますか。",           contoh_arti:"Apakah ada rasa gatal?",              kategori:"kondisi_tubuh" },
  { id:"070", kanji:"体温",   yomkata:"たいおん",  arti:"suhu tubuh",              contoh:"体温を測りますね。",             contoh_arti:"Saya ukur suhu tubuh ya.",            kategori:"kondisi_tubuh" },
  { id:"071", kanji:"脈拍",   yomkata:"みゃくはく",arti:"denyut nadi",             contoh:"脈拍を測りますね。",             contoh_arti:"Saya ukur denyut nadi ya.",           kategori:"kondisi_tubuh" },
  { id:"072", kanji:"呼吸",   yomkata:"こきゅう",  arti:"pernapasan",              contoh:"呼吸が速いですね。",             contoh_arti:"Pernapasan Anda cepat ya.",           kategori:"kondisi_tubuh" },
  { id:"073", kanji:"測定",   yomkata:"そくてい",  arti:"pengukuran",              contoh:"血圧の測定をします。",           contoh_arti:"Saya ukur tekanan darah.",            kategori:"kondisi_tubuh" },
  { id:"074", kanji:"体調",   yomkata:"たいちょう",arti:"kondisi tubuh",           contoh:"今日の体調はいかがですか。",     contoh_arti:"Bagaimana kondisi Anda hari ini?",    kategori:"kondisi_tubuh" },
  { id:"075", kanji:"表情",   yomkata:"ひょうじょう",arti:"ekspresi wajah",        contoh:"表情が暗いですね。",             contoh_arti:"Ekspresi Anda terlihat murung ya.",   kategori:"kondisi_tubuh" },
  { id:"076", kanji:"下痢",   yomkata:"げり",      arti:"diare",                   contoh:"下痢が続いていますか。",         contoh_arti:"Apakah diare terus berlanjut?",       kategori:"kondisi_tubuh" },
  { id:"077", kanji:"便秘",   yomkata:"べんぴ",    arti:"sembelit",                contoh:"便秘が続いていますか。",         contoh_arti:"Apakah sembelit terus berlanjut?",    kategori:"kondisi_tubuh" },
  { id:"078", kanji:"失禁",   yomkata:"しっきん",  arti:"inkontinensia",           contoh:"失禁がありましたか。",           contoh_arti:"Apakah ada inkontinensia?",           kategori:"kondisi_tubuh" },
  { id:"079", kanji:"やけど", yomkata:"やけど",    arti:"luka bakar",              contoh:"やけどしていませんか。",         contoh_arti:"Apakah Anda terluka bakar?",          kategori:"kondisi_tubuh" },
  { id:"080", kanji:"骨折",   yomkata:"こっせつ",  arti:"patah tulang",            contoh:"骨折かもしれません。",           contoh_arti:"Mungkin ada patah tulang.",           kategori:"kondisi_tubuh" },
  { id:"081", kanji:"転倒",   yomkata:"てんとう",  arti:"jatuh/terjatuh",          contoh:"転倒しないよう気をつけて。",     contoh_arti:"Hati-hati agar tidak jatuh.",         kategori:"kondisi_tubuh" },
  { id:"082", kanji:"麻痺",   yomkata:"まひ",      arti:"kelumpuhan/paralisis",    contoh:"麻痺がある側を患側といいます。", contoh_arti:"Sisi yang lumpuh disebut sisi sakit.", kategori:"kondisi_tubuh" },

  // =============================================
  // KATEGORI: mobilisasi (Alat & gerakan)
  // =============================================
  { id:"083", kanji:"ベッド",           yomkata:"ベッド",           arti:"tempat tidur",          contoh:"ベッドに横になりましょうか。",          contoh_arti:"Boleh kita berbaring di tempat tidur?",  kategori:"mobilisasi" },
  { id:"084", kanji:"枕",               yomkata:"まくら",           arti:"bantal",                contoh:"枕を変えましょうか。",                   contoh_arti:"Boleh saya ganti bantalnya?",             kategori:"mobilisasi" },
  { id:"085", kanji:"オーバーテーブル", yomkata:"オーバーテーブル", arti:"meja makan pasien",     contoh:"オーバーテーブルを片づけますね。",       contoh_arti:"Saya bereskan meja makan pasien ya.",    kategori:"mobilisasi" },
  { id:"086", kanji:"毛布",             yomkata:"もうふ",           arti:"selimut",               contoh:"毛布をかけますね。",                     contoh_arti:"Saya selimuti Anda ya.",                  kategori:"mobilisasi" },
  { id:"087", kanji:"シーツ",           yomkata:"シーツ",           arti:"seprai",                contoh:"シーツを交換しましょうか。",             contoh_arti:"Boleh saya ganti seprainya?",             kategori:"mobilisasi" },
  { id:"088", kanji:"床頭台",           yomkata:"しょうとうだい",   arti:"meja samping tempat tidur",contoh:"床頭台の上を片づけます。",            contoh_arti:"Saya bereskan meja samping ya.",          kategori:"mobilisasi" },
  { id:"089", kanji:"サイドレール",     yomkata:"サイドレール",     arti:"pagar tempat tidur",    contoh:"サイドレールを上げますね。",             contoh_arti:"Saya naikkan pagar tempat tidur ya.",    kategori:"mobilisasi" },
  { id:"090", kanji:"布団",             yomkata:"ふとん",           arti:"kasur/futon",           contoh:"布団をかけましょうか。",                 contoh_arti:"Boleh saya pasangkan kasur?",             kategori:"mobilisasi" },
  { id:"091", kanji:"マットレス",       yomkata:"マットレス",       arti:"matras",                contoh:"マットレスを確認しますね。",             contoh_arti:"Saya cek matrasnya ya.",                  kategori:"mobilisasi" },
  { id:"092", kanji:"車椅子",           yomkata:"くるまいす",       arti:"kursi roda",            contoh:"車椅子に乗りましょうか。",               contoh_arti:"Boleh kita naik kursi roda?",             kategori:"mobilisasi" },
  { id:"093", kanji:"杖",               yomkata:"つえ",             arti:"tongkat",               contoh:"杖を持ってください。",                   contoh_arti:"Tolong pegang tongkat.",                  kategori:"mobilisasi" },
  { id:"094", kanji:"歩行器",           yomkata:"ほこうき",         arti:"alat bantu jalan",      contoh:"歩行器を使いましょうか。",               contoh_arti:"Boleh kita pakai alat bantu jalan?",     kategori:"mobilisasi" },
  { id:"095", kanji:"ストレッチャー",   yomkata:"ストレッチャー",   arti:"brankar",               contoh:"ストレッチャーに移りましょう。",         contoh_arti:"Ayo pindah ke brankar.",                  kategori:"mobilisasi" },
  { id:"096", kanji:"移動用リフト",     yomkata:"いどうようリフト", arti:"alat pemindah",         contoh:"移動用リフトを使いますね。",             contoh_arti:"Saya pakai alat pemindah ya.",            kategori:"mobilisasi" },
  { id:"097", kanji:"スライディングボード",yomkata:"スライディングボード",arti:"papan penggeser", contoh:"スライディングボードで移動しましょう。",contoh_arti:"Ayo pindah dengan papan penggeser.",      kategori:"mobilisasi" },
  { id:"098", kanji:"スライディングシート",yomkata:"スライディングシート",arti:"kain penggeser",  contoh:"スライディングシートを敷きますね。",     contoh_arti:"Saya pasang kain penggeser ya.",          kategori:"mobilisasi" },
  { id:"099", kanji:"あおむけ",         yomkata:"あおむけ",         arti:"telentang / posisi supinasi", contoh:"あおむけになってください。",       contoh_arti:"Tolong berbaring telentang.",             kategori:"mobilisasi" },
  { id:"100", kanji:"うつぶせ",         yomkata:"うつぶせ",         arti:"tengkurap / posisi pronasi",  contoh:"うつぶせになれますか。",           contoh_arti:"Bisakah Anda tengkurap?",                 kategori:"mobilisasi" },
  { id:"101", kanji:"横向き",           yomkata:"よこむき",         arti:"miring ke samping",     contoh:"横向きになりましょうか。",               contoh_arti:"Boleh kita miring ke samping?",           kategori:"mobilisasi" },
  { id:"102", kanji:"体位",             yomkata:"たいい",           arti:"posisi tubuh",          contoh:"体位を変えましょうか。",                 contoh_arti:"Boleh kita ganti posisi tubuh?",          kategori:"mobilisasi" },
  { id:"103", kanji:"重心",             yomkata:"じゅうしん",       arti:"titik berat",           contoh:"重心を移動させますね。",                 contoh_arti:"Saya pindahkan titik beratnya ya.",       kategori:"mobilisasi" },
  { id:"104", kanji:"座位",             yomkata:"ざい",             arti:"posisi duduk",          contoh:"座位をとりましょうか。",                 contoh_arti:"Boleh kita duduk?",                       kategori:"mobilisasi" },
  { id:"105", kanji:"立位",             yomkata:"りつい",           arti:"posisi berdiri",        contoh:"立位で練習しましょう。",                 contoh_arti:"Ayo berlatih berdiri.",                   kategori:"mobilisasi" },
  { id:"106", kanji:"端座位",           yomkata:"たんざい",         arti:"posisi duduk tepi tempat tidur", contoh:"端座位で少し練習しましょう。", contoh_arti:"Ayo berlatih duduk di tepi kasur.",      kategori:"mobilisasi" },
  { id:"107", kanji:"患側",             yomkata:"かんそく",         arti:"sisi yang sakit/lumpuh",contoh:"患側から着替えましょう。",               contoh_arti:"Ayo berganti pakaian dari sisi yang sakit.", kategori:"mobilisasi" },
  { id:"108", kanji:"健側",             yomkata:"けんそく",         arti:"sisi yang sehat",       contoh:"健側から先に動きましょう。",             contoh_arti:"Ayo gerakkan sisi yang sehat terlebih dulu.", kategori:"mobilisasi" },

  // =============================================
  // KATEGORI: makan_minum (Perawatan makan)
  // =============================================
  { id:"109", kanji:"テーブル",     yomkata:"テーブル",   arti:"meja",                  contoh:"テーブルを拭きますね。",               contoh_arti:"Saya lap meja ya.",                     kategori:"makan_minum" },
  { id:"110", kanji:"椅子",         yomkata:"いす",       arti:"kursi",                 contoh:"椅子に座りましょうか。",               contoh_arti:"Boleh kita duduk di kursi?",             kategori:"makan_minum" },
  { id:"111", kanji:"茶碗",         yomkata:"ちゃわん",   arti:"mangkuk nasi",          contoh:"茶碗にご飯をよそいますね。",           contoh_arti:"Saya isikan nasi ke mangkuk ya.",       kategori:"makan_minum" },
  { id:"112", kanji:"すいのみ",     yomkata:"すいのみ",   arti:"cangkir khusus pasien", contoh:"すいのみでお茶を飲みましょうか。",     contoh_arti:"Boleh minum teh dengan cangkir khusus?",kategori:"makan_minum" },
  { id:"113", kanji:"お椀",         yomkata:"おわん",     arti:"mangkuk sup",           contoh:"お椀のお味噌汁ですよ。",               contoh_arti:"Ini sup miso di mangkuknya.",           kategori:"makan_minum" },
  { id:"114", kanji:"カップ",       yomkata:"カップ",     arti:"cangkir bertangkai",    contoh:"カップに牛乳を入れますね。",           contoh_arti:"Saya tuangkan susu ke cangkir ya.",     kategori:"makan_minum" },
  { id:"115", kanji:"コップ",       yomkata:"コップ",     arti:"gelas",                 contoh:"コップに水を入れましょうか。",         contoh_arti:"Boleh saya isikan air ke gelas?",       kategori:"makan_minum" },
  { id:"116", kanji:"湯呑",         yomkata:"ゆのみ",     arti:"cangkir teh",           contoh:"湯呑にお茶を入れますね。",             contoh_arti:"Saya isikan teh ke cangkir ya.",        kategori:"makan_minum" },
  { id:"117", kanji:"皿",           yomkata:"さら",       arti:"piring",                contoh:"お皿を出しますね。",                   contoh_arti:"Saya keluarkan piringnya ya.",           kategori:"makan_minum" },
  { id:"118", kanji:"箸",           yomkata:"はし",       arti:"sumpit",                contoh:"箸を使えますか。",                     contoh_arti:"Bisakah Anda menggunakan sumpit?",       kategori:"makan_minum" },
  { id:"119", kanji:"スプーン",     yomkata:"スプーン",   arti:"sendok",                contoh:"スプーンを持ってください。",           contoh_arti:"Tolong pegang sendoknya.",               kategori:"makan_minum" },
  { id:"120", kanji:"フォーク",     yomkata:"フォーク",   arti:"garpu",                 contoh:"フォークでいいですか。",               contoh_arti:"Apakah garpu boleh?",                   kategori:"makan_minum" },
  { id:"121", kanji:"炊飯器",       yomkata:"すいはんき", arti:"rice cooker",           contoh:"炊飯器のご飯が炊けましたよ。",         contoh_arti:"Nasi di rice cooker sudah matang.",     kategori:"makan_minum" },
  { id:"122", kanji:"やかん",       yomkata:"やかん",     arti:"ketel",                 contoh:"やかんのお湯が沸きましたよ。",         contoh_arti:"Air di ketel sudah mendidih.",          kategori:"makan_minum" },
  { id:"123", kanji:"鍋",           yomkata:"なべ",       arti:"panci/wajan",           contoh:"鍋でスープを温めますね。",             contoh_arti:"Saya hangatkan sup di panci ya.",       kategori:"makan_minum" },
  { id:"124", kanji:"調味料",       yomkata:"ちょうみりょう",arti:"bumbu/penyedap",     contoh:"調味料は使いますか。",                 contoh_arti:"Apakah Anda pakai bumbu?",               kategori:"makan_minum" },
  { id:"125", kanji:"エプロン",     yomkata:"エプロン",   arti:"celemek",               contoh:"エプロンをつけましょうか。",           contoh_arti:"Boleh saya pasangkan celemek?",         kategori:"makan_minum" },
  { id:"126", kanji:"食札",         yomkata:"しょくさつ", arti:"label makanan pasien",  contoh:"食札を確認してから配膳します。",       contoh_arti:"Saya cek label makanan sebelum menyajikan.", kategori:"makan_minum" },
  { id:"127", kanji:"果物",         yomkata:"くだもの",   arti:"buah",                  contoh:"今日の果物はりんごですよ。",           contoh_arti:"Buah hari ini adalah apel.",            kategori:"makan_minum" },
  { id:"128", kanji:"主食",         yomkata:"しゅしょく", arti:"makanan pokok",         contoh:"主食はご飯ですか、パンですか。",       contoh_arti:"Makanan pokoknya nasi atau roti?",      kategori:"makan_minum" },
  { id:"129", kanji:"主菜",         yomkata:"しゅさい",   arti:"hidangan utama",        contoh:"今日の主菜は魚ですよ。",               contoh_arti:"Hidangan utama hari ini adalah ikan.",  kategori:"makan_minum" },
  { id:"130", kanji:"おしぼり",     yomkata:"おしぼり",   arti:"lap tangan basah",      contoh:"おしぼりで手を拭きましょう。",         contoh_arti:"Tolong lap tangan dengan lap basah.",   kategori:"makan_minum" },
  { id:"131", kanji:"布巾",         yomkata:"ふきん",     arti:"kain lap/serbet",       contoh:"布巾でテーブルを拭きます。",           contoh_arti:"Saya lap meja dengan serbet.",          kategori:"makan_minum" },
  { id:"132", kanji:"副菜",         yomkata:"ふくさい",   arti:"lauk pelengkap",        contoh:"副菜はかぼちゃですよ。",               contoh_arti:"Lauk pelengkapnya adalah labu kuning.",  kategori:"makan_minum" },
  { id:"133", kanji:"汁物",         yomkata:"しるもの",   arti:"sup/kuah",              contoh:"汁物は熱いですよ、気をつけて。",       contoh_arti:"Supnya panas, hati-hati ya.",           kategori:"makan_minum" },
  { id:"134", kanji:"配膳車",       yomkata:"はいぜんしゃ",arti:"kereta makanan",       contoh:"配膳車で食事を運びます。",             contoh_arti:"Saya bawa makanan dengan kereta.",      kategori:"makan_minum" },
  { id:"135", kanji:"ミキサー",     yomkata:"ミキサー",   arti:"blender",               contoh:"ミキサー食にしますか。",               contoh_arti:"Apakah mau makanan blender?",           kategori:"makan_minum" },

  // =============================================
  // KATEGORI: BAB_BAK (Perawatan ekskresi/toilet)
  // =============================================
  { id:"136", kanji:"トイレ",           yomkata:"トイレ",           arti:"toilet/WC",               contoh:"トイレに行きたいですか。",             contoh_arti:"Apakah Anda ingin ke toilet?",         kategori:"BAB_BAK" },
  { id:"137", kanji:"トイレットペーパー",yomkata:"トイレットペーパー",arti:"kertas toilet",           contoh:"トイレットペーパーを取ってください。", contoh_arti:"Tolong ambil kertas toiletnya.",       kategori:"BAB_BAK" },
  { id:"138", kanji:"手すり",           yomkata:"てすり",           arti:"pegangan tangan/rel",     contoh:"手すりを持ってください。",             contoh_arti:"Tolong pegang relingnya.",             kategori:"BAB_BAK" },
  { id:"139", kanji:"便器",             yomkata:"べんき",           arti:"dudukan toilet",          contoh:"便器に座りましょうか。",               contoh_arti:"Boleh kita duduk di toilet?",          kategori:"BAB_BAK" },
  { id:"140", kanji:"便座",             yomkata:"べんざ",           arti:"tutup dudukan toilet",    contoh:"便座が冷たいですか。",                 contoh_arti:"Apakah dudukan toilet dingin?",        kategori:"BAB_BAK" },
  { id:"141", kanji:"おむつ交換車",     yomkata:"おむつこうかんしゃ",arti:"kereta ganti popok",     contoh:"おむつ交換車を持ってきますね。",       contoh_arti:"Saya ambilkan kereta ganti popok ya.", kategori:"BAB_BAK" },
  { id:"142", kanji:"汚物入れ",         yomkata:"おぶつい",         arti:"tempat sampah popok kotor",contoh:"汚物入れに捨てます。",                contoh_arti:"Saya buang ke tempat sampah kotor.",   kategori:"BAB_BAK" },
  { id:"143", kanji:"シャワーボトル",   yomkata:"シャワーボトル",   arti:"botol semprot",           contoh:"シャワーボトルで洗いますね。",         contoh_arti:"Saya cuci dengan botol semprot ya.",   kategori:"BAB_BAK" },
  { id:"144", kanji:"紙おむつ",         yomkata:"かみおむつ",       arti:"popok sekali pakai",      contoh:"紙おむつを交換しましょうか。",         contoh_arti:"Boleh kita ganti popok?",              kategori:"BAB_BAK" },
  { id:"145", kanji:"パッド",           yomkata:"パッド",           arti:"pembalut/pad",            contoh:"パッドを交換しますね。",               contoh_arti:"Saya ganti padnya ya.",                kategori:"BAB_BAK" },
  { id:"146", kanji:"尿器",             yomkata:"にょうき",         arti:"bô/pispot",               contoh:"尿器を使いますか。",                   contoh_arti:"Apakah Anda mau pakai pispot?",        kategori:"BAB_BAK" },
  { id:"147", kanji:"ポータブルトイレ", yomkata:"ポータブルトイレ", arti:"toilet portable",         contoh:"ポータブルトイレを使ってみますか。",   contoh_arti:"Mau mencoba toilet portable?",         kategori:"BAB_BAK" },
  { id:"148", kanji:"ナースコール",     yomkata:"ナースコール",     arti:"bel panggil perawat",     contoh:"何かあったらナースコールを押してください。",contoh_arti:"Jika ada sesuatu, tekan bel perawat.",kategori:"BAB_BAK" },

  // =============================================
  // KATEGORI: pakaian (Berpakaian)
  // =============================================
  { id:"149", kanji:"上着",       yomkata:"うわぎ",     arti:"pakaian luar/jaket",     contoh:"上着を着ましょうか。",               contoh_arti:"Boleh kita pakai jaket?",             kategori:"pakaian" },
  { id:"150", kanji:"シャツ",     yomkata:"シャツ",     arti:"kemeja/kaos",            contoh:"シャツを着替えましょうか。",         contoh_arti:"Boleh kita ganti kemeja?",            kategori:"pakaian" },
  { id:"151", kanji:"セーター",   yomkata:"セーター",   arti:"sweater",                contoh:"今日は寒いのでセーターを着ましょう。",contoh_arti:"Hari ini dingin, ayo pakai sweater.", kategori:"pakaian" },
  { id:"152", kanji:"パジャマ",   yomkata:"パジャマ",   arti:"piyama/baju tidur",      contoh:"パジャマに着替えましょうか。",       contoh_arti:"Boleh kita ganti piyama?",            kategori:"pakaian" },
  { id:"153", kanji:"肌着",       yomkata:"はだぎ",     arti:"pakaian dalam/kaos dalam",contoh:"肌着を交換しましょうか。",           contoh_arti:"Boleh kita ganti pakaian dalam?",     kategori:"pakaian" },
  { id:"154", kanji:"浴衣",       yomkata:"ゆかた",     arti:"yukata/kimono kasual",   contoh:"浴衣を着ましょうか。",               contoh_arti:"Boleh kita pakai yukata?",            kategori:"pakaian" },
  { id:"155", kanji:"パンツ",     yomkata:"パンツ",     arti:"celana dalam",           contoh:"パンツを交換しますね。",             contoh_arti:"Saya ganti celana dalam ya.",         kategori:"pakaian" },
  { id:"156", kanji:"靴",         yomkata:"くつ",       arti:"sepatu",                 contoh:"靴を履きましょうか。",               contoh_arti:"Boleh kita pakai sepatu?",            kategori:"pakaian" },
  { id:"157", kanji:"靴下",       yomkata:"くつした",   arti:"kaos kaki",              contoh:"靴下を履きましょうか。",             contoh_arti:"Boleh kita pakai kaos kaki?",         kategori:"pakaian" },
  { id:"158", kanji:"ズボン",     yomkata:"ズボン",     arti:"celana panjang",         contoh:"ズボンを上げますね。",               contoh_arti:"Saya naikkan celananya ya.",           kategori:"pakaian" },
  { id:"159", kanji:"スカート",   yomkata:"スカート",   arti:"rok",                    contoh:"スカートを穿きましょうか。",         contoh_arti:"Boleh kita pakai rok?",               kategori:"pakaian" },
  { id:"160", kanji:"上ばき",     yomkata:"うわばき",   arti:"sepatu dalam ruangan",   contoh:"上ばきに履き替えましょう。",         contoh_arti:"Ayo ganti ke sepatu dalam.",          kategori:"pakaian" },
  { id:"161", kanji:"スリッパ",   yomkata:"スリッパ",   arti:"sandal rumah",           contoh:"スリッパを履いてください。",         contoh_arti:"Tolong pakai sandalnya.",             kategori:"pakaian" },
  { id:"162", kanji:"マフラー",   yomkata:"マフラー",   arti:"syal",                   contoh:"マフラーをつけましょうか。",         contoh_arti:"Boleh saya pasangkan syal?",          kategori:"pakaian" },
  { id:"163", kanji:"手袋",       yomkata:"てぶくろ",   arti:"sarung tangan",          contoh:"手袋をはめましょうか。",             contoh_arti:"Boleh saya pasangkan sarung tangan?", kategori:"pakaian" },
  { id:"164", kanji:"ベルト",     yomkata:"ベルト",     arti:"ikat pinggang",          contoh:"ベルトを締めましょうか。",           contoh_arti:"Boleh saya pasangkan ikat pinggang?", kategori:"pakaian" },
  { id:"165", kanji:"ゴム",       yomkata:"ゴム",       arti:"karet (celana)",         contoh:"ゴムがきつくないですか。",           contoh_arti:"Apakah karetnya tidak terlalu ketat?",kategori:"pakaian" },
  { id:"166", kanji:"紐",         yomkata:"ひも",       arti:"tali",                   contoh:"紐を結びますね。",                   contoh_arti:"Saya ikat talinya ya.",               kategori:"pakaian" },
  { id:"167", kanji:"えり",       yomkata:"えり",       arti:"kerah baju",             contoh:"えりが曲がっていますよ。",           contoh_arti:"Kerah baju Anda miring ya.",          kategori:"pakaian" },
  { id:"168", kanji:"そで",       yomkata:"そで",       arti:"lengan baju",            contoh:"そでを通しますね。",                 contoh_arti:"Saya masukkan lengan baju ya.",       kategori:"pakaian" },
  { id:"169", kanji:"そで口",     yomkata:"そでぐち",   arti:"manset/ujung lengan baju",contoh:"そで口を直しますね。",               contoh_arti:"Saya rapikan ujung lengan baju ya.",  kategori:"pakaian" },
  { id:"170", kanji:"ボタン",     yomkata:"ボタン",     arti:"kancing",                contoh:"ボタンは自分でできますか。",         contoh_arti:"Bisakah Anda mengancingkan sendiri?", kategori:"pakaian" },
  { id:"171", kanji:"ファスナー", yomkata:"ファスナー", arti:"ritsleting",             contoh:"ファスナーを上げますね。",           contoh_arti:"Saya naikkan ritsletingnya ya.",      kategori:"pakaian" },

  // =============================================
  // KATEGORI: mandi_kebersihan (Mandi & kebersihan)
  // =============================================
  { id:"172", kanji:"脱衣室",       yomkata:"だついしつ",   arti:"ruang ganti",             contoh:"脱衣室で服を脱ぎましょう。",         contoh_arti:"Ayo buka baju di ruang ganti.",        kategori:"mandi_kebersihan" },
  { id:"173", kanji:"バスタオル",   yomkata:"バスタオル",   arti:"handuk mandi",            contoh:"バスタオルで体を拭きますね。",       contoh_arti:"Saya lap badan Anda dengan handuk ya.",kategori:"mandi_kebersihan" },
  { id:"174", kanji:"ドライヤー",   yomkata:"ドライヤー",   arti:"pengering rambut",        contoh:"ドライヤーで髪を乾かしますね。",     contoh_arti:"Saya keringkan rambut Anda ya.",       kategori:"mandi_kebersihan" },
  { id:"175", kanji:"シャンプー",   yomkata:"シャンプー",   arti:"sampo",                   contoh:"シャンプーをつけますね。",           contoh_arti:"Saya tuangkan samponya ya.",           kategori:"mandi_kebersihan" },
  { id:"176", kanji:"リンス",       yomkata:"リンス",       arti:"kondisioner rambut",      contoh:"リンスをしますね。",                 contoh_arti:"Saya pakai kondisioner ya.",           kategori:"mandi_kebersihan" },
  { id:"177", kanji:"鏡",           yomkata:"かがみ",       arti:"cermin",                  contoh:"鏡で確認してください。",             contoh_arti:"Tolong cek di cermin.",                kategori:"mandi_kebersihan" },
  { id:"178", kanji:"シャワー",     yomkata:"シャワー",     arti:"shower",                  contoh:"シャワーをかけますね。",             contoh_arti:"Saya siramkan shower ya.",             kategori:"mandi_kebersihan" },
  { id:"179", kanji:"シャワーハット",yomkata:"シャワーハット",arti:"topi mandi",             contoh:"シャワーハットをかぶりますね。",     contoh_arti:"Saya pasangkan topi mandi ya.",        kategori:"mandi_kebersihan" },
  { id:"180", kanji:"タオル",       yomkata:"タオル",       arti:"handuk",                  contoh:"タオルで拭きますね。",               contoh_arti:"Saya lap dengan handuk ya.",           kategori:"mandi_kebersihan" },
  { id:"181", kanji:"バスマット",   yomkata:"バスマット",   arti:"keset kamar mandi",       contoh:"バスマットの上に立ってください。",   contoh_arti:"Tolong berdiri di atas keset.",        kategori:"mandi_kebersihan" },
  { id:"182", kanji:"洗面器",       yomkata:"せんめんき",   arti:"baskom",                  contoh:"洗面器にお湯を入れますね。",         contoh_arti:"Saya isikan air hangat ke baskom ya.", kategori:"mandi_kebersihan" },
  { id:"183", kanji:"シャワーチェア",yomkata:"シャワーチェア",arti:"kursi mandi",            contoh:"シャワーチェアに座りましょうか。",   contoh_arti:"Boleh kita duduk di kursi mandi?",    kategori:"mandi_kebersihan" },
  { id:"184", kanji:"せっけん",     yomkata:"せっけん",     arti:"sabun",                   contoh:"せっけんで洗いますね。",             contoh_arti:"Saya cuci dengan sabun ya.",           kategori:"mandi_kebersihan" },
  { id:"185", kanji:"浴そう",       yomkata:"よくそう",     arti:"bak mandi",               contoh:"浴そうに入りましょうか。",           contoh_arti:"Boleh kita masuk bak mandi?",          kategori:"mandi_kebersihan" },
  { id:"186", kanji:"浴室",         yomkata:"よくしつ",     arti:"kamar mandi",             contoh:"浴室は滑りやすいので気をつけて。",   contoh_arti:"Kamar mandi licin, hati-hati ya.",     kategori:"mandi_kebersihan" },
  { id:"187", kanji:"歯ブラシ",     yomkata:"はブラシ",     arti:"sikat gigi",              contoh:"歯ブラシを使いましょうか。",         contoh_arti:"Boleh kita pakai sikat gigi?",         kategori:"mandi_kebersihan" },
  { id:"188", kanji:"歯磨き粉",     yomkata:"はみがきこ",   arti:"pasta gigi",              contoh:"歯磨き粉をつけますね。",             contoh_arti:"Saya taruh pasta gigi ya.",            kategori:"mandi_kebersihan" },
  { id:"189", kanji:"シェーバー",   yomkata:"シェーバー",   arti:"alat cukur/shaver",       contoh:"シェーバーで髭を剃りましょうか。",   contoh_arti:"Boleh saya cukurkan kumis/jenggot?",   kategori:"mandi_kebersihan" },
  { id:"190", kanji:"化粧水",       yomkata:"けしょうすい", arti:"toner kulit",             contoh:"化粧水をつけましょうか。",           contoh_arti:"Boleh saya oleskan toner?",            kategori:"mandi_kebersihan" },
  { id:"191", kanji:"耳かき",       yomkata:"みみかき",     arti:"korek telinga",           contoh:"耳かきをしましょうか。",             contoh_arti:"Boleh saya bersihkan telinga?",        kategori:"mandi_kebersihan" },
  { id:"192", kanji:"爪切り",       yomkata:"つめきり",     arti:"gunting kuku",            contoh:"爪切りで爪を切りましょうか。",       contoh_arti:"Boleh saya potong kuku dengan gunting?",kategori:"mandi_kebersihan" },
  { id:"193", kanji:"クリーム",     yomkata:"クリーム",     arti:"krim pelembab",           contoh:"クリームを塗りましょうか。",         contoh_arti:"Boleh saya oleskan krim?",             kategori:"mandi_kebersihan" },
  { id:"194", kanji:"ブラシ",       yomkata:"ブラシ",       arti:"sikat rambut",            contoh:"ブラシで髪を整えましょうか。",       contoh_arti:"Boleh saya rapikan rambut?",           kategori:"mandi_kebersihan" },
  { id:"195", kanji:"くし",         yomkata:"くし",         arti:"sisir",                   contoh:"くしで髪を梳かしますね。",           contoh_arti:"Saya sisirkan rambut ya.",             kategori:"mandi_kebersihan" },

  // =============================================
  // KATEGORI: kehidupan_sehari (Kehidupan sehari-hari)
  // =============================================
  { id:"196", kanji:"戸",         yomkata:"と",         arti:"pintu",                contoh:"戸を開けてもいいですか。",             contoh_arti:"Boleh saya buka pintunya?",            kategori:"kehidupan_sehari" },
  { id:"197", kanji:"窓",         yomkata:"まど",       arti:"jendela",              contoh:"窓を開けてもいいですか。",             contoh_arti:"Boleh saya buka jendelanya?",          kategori:"kehidupan_sehari" },
  { id:"198", kanji:"網戸",       yomkata:"あみど",     arti:"pintu kasa/jendela kasa",contoh:"網戸を閉めますね。",                 contoh_arti:"Saya tutup pintu kasanya ya.",         kategori:"kehidupan_sehari" },
  { id:"199", kanji:"電気",       yomkata:"でんき",     arti:"lampu/listrik",        contoh:"電気を消しましょうか。",               contoh_arti:"Boleh saya matikan lampunya?",         kategori:"kehidupan_sehari" },
  { id:"200", kanji:"カーテン",   yomkata:"カーテン",   arti:"tirai/gorden",         contoh:"カーテンを開けますね。",               contoh_arti:"Saya buka gordennya ya.",              kategori:"kehidupan_sehari" },
  { id:"201", kanji:"テレビ",     yomkata:"テレビ",     arti:"televisi",             contoh:"テレビをつけましょうか。",             contoh_arti:"Boleh saya nyalakan televisi?",        kategori:"kehidupan_sehari" },
  { id:"202", kanji:"携帯電話",   yomkata:"けいたいでんわ",arti:"telepon genggam",   contoh:"携帯電話を充電しますね。",             contoh_arti:"Saya cas handphone ya.",               kategori:"kehidupan_sehari" },
  { id:"203", kanji:"タンス",     yomkata:"タンス",     arti:"lemari/laci",          contoh:"タンスから着替えを出しますね。",       contoh_arti:"Saya ambilkan baju ganti dari lemari.", kategori:"kehidupan_sehari" },
  { id:"204", kanji:"ごみ箱",     yomkata:"ごみばこ",   arti:"tempat sampah",        contoh:"ごみ箱を空にしますね。",               contoh_arti:"Saya kosongkan tempat sampah ya.",     kategori:"kehidupan_sehari" },
  { id:"205", kanji:"洗濯機",     yomkata:"せんたくき", arti:"mesin cuci",           contoh:"洗濯機に入れますね。",                 contoh_arti:"Saya masukkan ke mesin cuci ya.",      kategori:"kehidupan_sehari" },
  { id:"206", kanji:"乾燥機",     yomkata:"かんそうき", arti:"mesin pengering",      contoh:"乾燥機で乾かしますね。",               contoh_arti:"Saya keringkan di mesin pengering ya.",kategori:"kehidupan_sehari" },
  { id:"207", kanji:"ティッシュペーパー",yomkata:"ティッシュペーパー",arti:"tisu/tissue",contoh:"ティッシュペーパーを使いますか。",   contoh_arti:"Apakah Anda mau pakai tisu?",          kategori:"kehidupan_sehari" },
  { id:"208", kanji:"洗剤",       yomkata:"せんざい",   arti:"detergen",             contoh:"洗剤を入れて洗います。",               contoh_arti:"Saya cuci dengan detergen.",           kategori:"kehidupan_sehari" },
  { id:"209", kanji:"水道",       yomkata:"すいどう",   arti:"air PAM/keran",        contoh:"水道の水で洗いましょう。",             contoh_arti:"Ayo cuci dengan air keran.",           kategori:"kehidupan_sehari" },
  { id:"210", kanji:"雑巾",       yomkata:"ぞうきん",   arti:"kain lap/lap lantai",  contoh:"雑巾で床を拭きますね。",               contoh_arti:"Saya lap lantai dengan kain lap ya.", kategori:"kehidupan_sehari" },
  { id:"211", kanji:"バケツ",     yomkata:"バケツ",     arti:"ember",                contoh:"バケツに水を入れますね。",             contoh_arti:"Saya isikan air ke ember ya.",         kategori:"kehidupan_sehari" },
  { id:"212", kanji:"湯たんぽ",   yomkata:"ゆたんぽ",   arti:"botol air hangat",     contoh:"湯たんぽを足元に置きますね。",         contoh_arti:"Saya letakkan botol hangat di kaki ya.",kategori:"kehidupan_sehari" },
  { id:"213", kanji:"新聞",       yomkata:"しんぶん",   arti:"koran",                contoh:"新聞を読みますか。",                   contoh_arti:"Apakah Anda mau baca koran?",          kategori:"kehidupan_sehari" },
  { id:"214", kanji:"写真",       yomkata:"しゃしん",   arti:"foto",                 contoh:"写真を飾りましょうか。",               contoh_arti:"Boleh saya pasang foto?",              kategori:"kehidupan_sehari" },
  { id:"215", kanji:"父",         yomkata:"ちち",       arti:"ayah",                 contoh:"お父さんはいつ来ますか。",             contoh_arti:"Kapan ayah datang?",                   kategori:"kehidupan_sehari" },
  { id:"216", kanji:"母",         yomkata:"はは",       arti:"ibu",                  contoh:"お母さんに連絡しましょうか。",         contoh_arti:"Boleh saya hubungi ibu Anda?",         kategori:"kehidupan_sehari" },
  { id:"217", kanji:"夫",         yomkata:"おっと",     arti:"suami",                contoh:"ご主人はいつ面会に来ますか。",         contoh_arti:"Kapan suami Anda berkunjung?",         kategori:"kehidupan_sehari" },
  { id:"218", kanji:"妻",         yomkata:"つま",       arti:"istri",                contoh:"奥さんが来られていますよ。",           contoh_arti:"Istri Anda sudah datang.",             kategori:"kehidupan_sehari" },
  { id:"219", kanji:"息子",       yomkata:"むすこ",     arti:"anak laki-laki",       contoh:"息子さんから電話がありましたよ。",     contoh_arti:"Ada telepon dari putra Anda.",         kategori:"kehidupan_sehari" },
  { id:"220", kanji:"娘",         yomkata:"むすめ",     arti:"anak perempuan",       contoh:"娘さんが面会に来ていますよ。",         contoh_arti:"Putri Anda datang berkunjung.",        kategori:"kehidupan_sehari" },
  { id:"221", kanji:"孫",         yomkata:"まご",       arti:"cucu",                 contoh:"お孫さんが来ましたよ。",               contoh_arti:"Cucu Anda datang.",                    kategori:"kehidupan_sehari" },
  { id:"222", kanji:"兄",         yomkata:"あに",       arti:"kakak laki-laki",      contoh:"お兄さんが面会に来ています。",         contoh_arti:"Kakak laki-laki Anda berkunjung.",    kategori:"kehidupan_sehari" },
  { id:"223", kanji:"弟",         yomkata:"おとうと",   arti:"adik laki-laki",       contoh:"弟さんから連絡がありましたよ。",       contoh_arti:"Ada pesan dari adik laki-laki.",       kategori:"kehidupan_sehari" },
  { id:"224", kanji:"姉",         yomkata:"あね",       arti:"kakak perempuan",      contoh:"お姉さんが来ていますよ。",             contoh_arti:"Kakak perempuan Anda datang.",         kategori:"kehidupan_sehari" },
  { id:"225", kanji:"妹",         yomkata:"いもうと",   arti:"adik perempuan",       contoh:"妹さんが電話してきましたよ。",         contoh_arti:"Adik perempuan Anda menelepon.",       kategori:"kehidupan_sehari" },

  // =============================================
  // KATEGORI: pekerjaan (Pekerjaan & komunikasi)
  // =============================================
  { id:"226", kanji:"医師",         yomkata:"いし",         arti:"dokter",                  contoh:"医師に報告します。",               contoh_arti:"Saya laporkan ke dokter.",              kategori:"pekerjaan" },
  { id:"227", kanji:"看護師",       yomkata:"かんごし",     arti:"perawat/nurse",           contoh:"看護師に相談しましょう。",         contoh_arti:"Ayo konsultasi ke perawat.",            kategori:"pekerjaan" },
  { id:"228", kanji:"介護福祉士",   yomkata:"かいごふくしし",arti:"perawat lansia bersertifikat",contoh:"介護福祉士の指示に従います。",  contoh_arti:"Saya ikuti petunjuk perawat.",          kategori:"pekerjaan" },
  { id:"229", kanji:"介護職員",     yomkata:"かいごしょくいん",arti:"staf perawatan",       contoh:"介護職員が対応します。",           contoh_arti:"Staf perawatan akan menangani.",        kategori:"pekerjaan" },
  { id:"230", kanji:"理学療法士",   yomkata:"りがくりょうほうし",arti:"fisioterapis (PT)",  contoh:"理学療法士のリハビリがあります。",  contoh_arti:"Ada rehabilitasi dengan fisioterapis.", kategori:"pekerjaan" },
  { id:"231", kanji:"作業療法士",   yomkata:"さぎょうりょうほうし",arti:"terapis kerja (OT)",contoh:"作業療法士に相談します。",         contoh_arti:"Saya konsultasi dengan terapis kerja.", kategori:"pekerjaan" },
  { id:"232", kanji:"言語聴覚士",   yomkata:"げんごちょうかくし",arti:"terapis wicara (ST)",contoh:"言語聴覚士が来ています。",          contoh_arti:"Terapis wicara sudah datang.",          kategori:"pekerjaan" },
  { id:"233", kanji:"ケアマネジャー",yomkata:"ケアマネジャー",arti:"manajer perawatan",    contoh:"ケアマネジャーに連絡します。",     contoh_arti:"Saya hubungi manajer perawatan.",       kategori:"pekerjaan" },
  { id:"234", kanji:"栄養士",       yomkata:"えいようし",   arti:"ahli gizi",               contoh:"栄養士に食事の相談をします。",     contoh_arti:"Saya konsultasi makanan ke ahli gizi.", kategori:"pekerjaan" },
  { id:"235", kanji:"相談員",       yomkata:"そうだんいん", arti:"konselor/petugas konsultasi",contoh:"相談員に話してみましょう。",    contoh_arti:"Coba bicarakan dengan konselor.",       kategori:"pekerjaan" },
  { id:"236", kanji:"利用者",       yomkata:"りようしゃ",   arti:"pengguna layanan",        contoh:"利用者さんの体調を確認します。",   contoh_arti:"Saya periksa kondisi pengguna layanan.",kategori:"pekerjaan" },
  { id:"237", kanji:"患者",         yomkata:"かんじゃ",     arti:"pasien",                  contoh:"患者さんが呼んでいますよ。",       contoh_arti:"Pasien memanggil Anda.",                kategori:"pekerjaan" },
  { id:"238", kanji:"報告",         yomkata:"ほうこく",     arti:"laporan/melapor",         contoh:"すぐに報告してください。",         contoh_arti:"Tolong segera melaporkan.",             kategori:"pekerjaan" },
  { id:"239", kanji:"連絡",         yomkata:"れんらく",     arti:"kontak/menghubungi",      contoh:"家族に連絡します。",               contoh_arti:"Saya hubungi keluarga.",                kategori:"pekerjaan" },
  { id:"240", kanji:"相談",         yomkata:"そうだん",     arti:"konsultasi/berdiskusi",   contoh:"先輩に相談してください。",         contoh_arti:"Tolong konsultasi dengan senior.",      kategori:"pekerjaan" },
  { id:"241", kanji:"確認",         yomkata:"かくにん",     arti:"konfirmasi/memeriksa",    contoh:"もう一度確認します。",             contoh_arti:"Saya periksa sekali lagi.",             kategori:"pekerjaan" },
  { id:"242", kanji:"指導",         yomkata:"しどう",       arti:"bimbingan/petunjuk",      contoh:"先輩から指導を受けます。",         contoh_arti:"Saya terima bimbingan dari senior.",    kategori:"pekerjaan" },
  { id:"243", kanji:"助言",         yomkata:"じょげん",     arti:"saran/nasihat",           contoh:"アドバイスや助言をもらいます。",   contoh_arti:"Saya terima saran dan nasihat.",        kategori:"pekerjaan" },
  { id:"244", kanji:"申し送り",     yomkata:"もうしおくり", arti:"serah terima shift",      contoh:"申し送りを始めましょう。",         contoh_arti:"Ayo mulai serah terima.",               kategori:"pekerjaan" },
  { id:"245", kanji:"記録",         yomkata:"きろく",       arti:"catatan/pencatatan",      contoh:"記録をつけてください。",           contoh_arti:"Tolong buat catatannya.",               kategori:"pekerjaan" },
  { id:"246", kanji:"記録ファイル", yomkata:"きろくファイル",arti:"file catatan",           contoh:"記録ファイルを確認します。",       contoh_arti:"Saya cek file catatan.",                kategori:"pekerjaan" },
  { id:"247", kanji:"棚",           yomkata:"たな",         arti:"rak",                     contoh:"棚の上に置いてください。",         contoh_arti:"Tolong letakkan di atas rak.",          kategori:"pekerjaan" },
  { id:"248", kanji:"鍵",           yomkata:"かぎ",         arti:"kunci",                   contoh:"鍵をかけてください。",             contoh_arti:"Tolong kunci.",                         kategori:"pekerjaan" },
  { id:"249", kanji:"名札",         yomkata:"なふだ",       arti:"kartu nama/papan nama",   contoh:"名札をつけてください。",           contoh_arti:"Tolong pasang kartu nama.",             kategori:"pekerjaan" },
  { id:"250", kanji:"AED",          yomkata:"エーイーディー",arti:"AED / mesin kejut jantung",contoh:"AEDの場所を確認しておきます。",  contoh_arti:"Saya cek lokasi AED.",                  kategori:"pekerjaan" },
  { id:"251", kanji:"シフト",       yomkata:"シフト",       arti:"jadwal shift",            contoh:"今月のシフトを確認します。",       contoh_arti:"Saya cek jadwal shift bulan ini.",      kategori:"pekerjaan" },
  { id:"252", kanji:"日勤",         yomkata:"にっきん",     arti:"shift siang",             contoh:"今日は日勤です。",                 contoh_arti:"Hari ini shift siang.",                 kategori:"pekerjaan" },
  { id:"253", kanji:"夜勤",         yomkata:"やきん",       arti:"shift malam",             contoh:"明日は夜勤があります。",           contoh_arti:"Besok ada shift malam.",                kategori:"pekerjaan" },
  { id:"254", kanji:"遅番",         yomkata:"おそばん",     arti:"shift sore/telat",        contoh:"今日は遅番です。",                 contoh_arti:"Hari ini shift sore.",                  kategori:"pekerjaan" },
  { id:"255", kanji:"早番",         yomkata:"はやばん",     arti:"shift pagi/awal",         contoh:"明日は早番です。",                 contoh_arti:"Besok shift pagi.",                     kategori:"pekerjaan" },
  { id:"256", kanji:"有給休暇",     yomkata:"ゆうきゅうきゅうか",arti:"cuti berbayar",       contoh:"有給休暇を取りたいです。",         contoh_arti:"Saya ingin mengambil cuti berbayar.",   kategori:"pekerjaan" },
  { id:"257", kanji:"公休",         yomkata:"こうきゅう",   arti:"libur resmi",             contoh:"来週は公休があります。",           contoh_arti:"Minggu depan ada libur resmi.",         kategori:"pekerjaan" },
  { id:"258", kanji:"遅刻",         yomkata:"ちこく",       arti:"terlambat",               contoh:"遅刻しないように気をつけます。",   contoh_arti:"Saya hati-hati agar tidak terlambat.",  kategori:"pekerjaan" },
  { id:"259", kanji:"早退",         yomkata:"そうたい",     arti:"pulang lebih awal",       contoh:"早退してもいいですか。",           contoh_arti:"Boleh saya pulang lebih awal?",         kategori:"pekerjaan" },
  { id:"260", kanji:"欠勤",         yomkata:"けっきん",     arti:"tidak masuk kerja",       contoh:"欠勤の連絡をします。",             contoh_arti:"Saya sampaikan info tidak masuk.",      kategori:"pekerjaan" },
  { id:"261", kanji:"病欠",         yomkata:"びょうけつ",   arti:"izin sakit",              contoh:"体調が悪くて病欠します。",         contoh_arti:"Kondisi buruk, saya izin sakit.",       kategori:"pekerjaan" },
  { id:"262", kanji:"カラオケ",     yomkata:"カラオケ",     arti:"karaoke",                 contoh:"カラオケをしましょうか。",         contoh_arti:"Boleh kita karaoke?",                   kategori:"pekerjaan" },
  { id:"263", kanji:"トランプ",     yomkata:"トランプ",     arti:"kartu remi",              contoh:"トランプゲームをしましょうか。",   contoh_arti:"Boleh kita main kartu?",                kategori:"pekerjaan" },
  { id:"264", kanji:"百人一首",     yomkata:"ひゃくにんいっしゅ",arti:"kartu puisi tradisional Jepang",contoh:"百人一首で遊びましょうか。",contoh_arti:"Boleh kita main hyakunin isshu?",       kategori:"pekerjaan" },
  { id:"265", kanji:"麻雀",         yomkata:"まーじゃん",   arti:"mahjong",                 contoh:"麻雀をしましょうか。",             contoh_arti:"Boleh kita main mahjong?",               kategori:"pekerjaan" },
  { id:"266", kanji:"習字",         yomkata:"しゅうじ",     arti:"kaligrafi Jepang",        contoh:"習字の時間ですよ。",               contoh_arti:"Ini waktunya kaligrafi.",               kategori:"pekerjaan" },

  // =============================================
  // (id 267 — pelengkap)
  // =============================================
  { id:"267", kanji:"しゃもじ",     yomkata:"しゃもじ",     arti:"centong nasi",            contoh:"しゃもじでご飯をよそいます。",     contoh_arti:"Saya ambil nasi dengan centong.",       kategori:"makan_minum" },
];

// Daftar kategori dengan label dan jumlah kosakata
const KATEGORI_INFO = {
  tubuh_luar:        { label: "Bagian Luar Tubuh",        labelJP: "からだの外側",           total: 0 },
  tubuh_dalam:       { label: "Organ Dalam",               labelJP: "からだの中",             total: 0 },
  kondisi_tubuh:     { label: "Kondisi & Pemeriksaan",     labelJP: "体調・確認",             total: 0 },
  mobilisasi:        { label: "Mobilisasi & Tempat Tidur", labelJP: "移動・ベッド周り",       total: 0 },
  makan_minum:       { label: "Makan & Minum",             labelJP: "食事介助",               total: 0 },
  BAB_BAK:           { label: "Toilet & Ekskresi",         labelJP: "排泄介助",               total: 0 },
  pakaian:           { label: "Pakaian & Berpakaian",      labelJP: "衣服の着脱",             total: 0 },
  mandi_kebersihan:  { label: "Mandi & Kebersihan",        labelJP: "入浴・清潔",             total: 0 },
  kehidupan_sehari:  { label: "Kehidupan Sehari-hari",     labelJP: "日常生活",               total: 0 },
  pekerjaan:         { label: "Pekerjaan & Komunikasi",    labelJP: "仕事・コミュニケーション", total: 0 },
};

// Hitung jumlah per kategori
VOCABULARY.forEach(v => {
  if (KATEGORI_INFO[v.kategori]) KATEGORI_INFO[v.kategori].total++;
});
